### ISSUE TITLE
Version of ependency maciejczyzewski/bottomline too restrictive

### ISSUE THREAD

**Issue by schugabe** [einpraegsam/google-image-grabber#1]
maciejczyzewski/bottomline is reqiured with ^0.0.9 and that prevents composer from updating it to newer versions like 0.2.3

The old 0.0.9 version generates warnings during composer install/update.

Pulling in this package just for the slug method is probably not necessary so maybe it would be better to get rid of this dependency.

**Comment by einpraegsam** [comment]
Thx, I just tagged 1.0.5 with updated dependencies to maciejczyzewski/bottomline
